trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - main
      - release/*
      - feature/*
      - hotfix/*
  paths:
    exclude:
      - README.md

pool:
  vmImage: "ubuntu-latest"

variables:
  DOCKER_CONTAINER_REGISTRY: "Decentralized Cloud Docker Hub"
  DOCKER_REPOSITORY_NAME: "decentralizedcloud/frontend"
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    version: latest
  ${{ if not(eq(variables['Build.SourceBranch'], 'refs/heads/main')) }}:
    version: $(GitVersion.SemVer)

steps:
  - task: GitVersion@5
    displayName: "Figure out GitVersion"
    inputs:
      runtime: "core"
      configFilePath: "./GitVersion.yml"

  - task: Docker@2
    displayName: "Build"
    inputs:
      repository: $(DOCKER_REPOSITORY_NAME)
      command: "build"
      Dockerfile: "$(system.defaultWorkingDirectory)/apps/admin/docker/Dockerfile"
      buildContext: "$(system.defaultWorkingDirectory)/apps/admin"
      arguments: "--build-arg VERSION=${{variables.version}}"
      tags: ${{variables.version}}

  - task: Docker@2
    displayName: "Test and coverage"
    inputs:
      repository: $(DOCKER_REPOSITORY_NAME)
      command: "build"
      Dockerfile: "$(system.defaultWorkingDirectory)/apps/admin/docker/Dockerfile.testAndCoverage"
      buildContext: "$(system.defaultWorkingDirectory)/apps/admin"
      arguments: "--build-arg COVERALLS_SERVICE_NAME=$(COVERALLS_SERVICE_NAME) --build-arg COVERALLS_REPO_TOKEN=$(COVERALLS_REPO_TOKEN)"

  - task: Docker@2
    displayName: "Docker login"
    inputs:
      containerRegistry: $(DOCKER_CONTAINER_REGISTRY)
      command: "login"

  - task: Docker@2
    displayName: "Push docker image"
    inputs:
      containerRegistry: $(DOCKER_CONTAINER_REGISTRY)
      repository: $(DOCKER_REPOSITORY_NAME)
      command: "push"
      tags: ${{variables.version}}

  - task: Docker@2
    displayName: "Docker logout"
    inputs:
      containerRegistry: $(DOCKER_CONTAINER_REGISTRY)
      command: "logout"

  - task: HelmInstaller@0
    displayName: "Installing helm"
    inputs:
      helmVersion: "3.5.2"
      installKubectl: false

  - task: Bash@3
    displayName: "Packaging helm"
    inputs:
      targetType: "inline"
      script: |
        helm package --destination "$(system.defaultWorkingDirectory)/chart-output" --app-version ${{variables.version}} "$(system.defaultWorkingDirectory)/apps/admin/helm-charts"

  - task: PublishPipelineArtifact@1
    displayName: "Publish helm artifact"
    inputs:
      targetPath: "$(system.defaultWorkingDirectory)/chart-output"
      artifact: "helm"
      publishLocation: "pipeline"
